export enum NotificationType {
    TEAM_INVITATION = 'TEAM_INVITATION',
	NEW_CHALLENGE_TEAM = 'NEW_CHALLENGE_TEAM',
    NEW_MEMBER_TEAM = 'NEW_MEMBER_TEAM',
    INVITATION_REJECTION = 'INVITATION_REJECTION',
    INVITATION_ACCEPTED = 'INVITATION_ACCEPTED'
}
